/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanVenueRouteImport } from './routes/plan.venue'
import { Route as PlanSideRouteImport } from './routes/plan.side'
import { Route as PlanReviewRouteImport } from './routes/plan.review'
import { Route as PlanOccasionRouteImport } from './routes/plan.occasion'
import { Route as PlanMealsRouteImport } from './routes/plan.meals'
import { Route as PlanIntroRouteImport } from './routes/plan.intro'
import { Route as PlanGuestsRouteImport } from './routes/plan.guests'
import { Route as PlanDatesRouteImport } from './routes/plan.dates'
import { Route as PlanConfirmRouteImport } from './routes/plan.confirm'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanVenueRoute = PlanVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => PlanRoute,
} as any)
const PlanSideRoute = PlanSideRouteImport.update({
  id: '/side',
  path: '/side',
  getParentRoute: () => PlanRoute,
} as any)
const PlanReviewRoute = PlanReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PlanRoute,
} as any)
const PlanOccasionRoute = PlanOccasionRouteImport.update({
  id: '/occasion',
  path: '/occasion',
  getParentRoute: () => PlanRoute,
} as any)
const PlanMealsRoute = PlanMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => PlanRoute,
} as any)
const PlanIntroRoute = PlanIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => PlanRoute,
} as any)
const PlanGuestsRoute = PlanGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => PlanRoute,
} as any)
const PlanDatesRoute = PlanDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => PlanRoute,
} as any)
const PlanConfirmRoute = PlanConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => PlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/plan/confirm': typeof PlanConfirmRoute
  '/plan/dates': typeof PlanDatesRoute
  '/plan/guests': typeof PlanGuestsRoute
  '/plan/intro': typeof PlanIntroRoute
  '/plan/meals': typeof PlanMealsRoute
  '/plan/occasion': typeof PlanOccasionRoute
  '/plan/review': typeof PlanReviewRoute
  '/plan/side': typeof PlanSideRoute
  '/plan/venue': typeof PlanVenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/plan/confirm': typeof PlanConfirmRoute
  '/plan/dates': typeof PlanDatesRoute
  '/plan/guests': typeof PlanGuestsRoute
  '/plan/intro': typeof PlanIntroRoute
  '/plan/meals': typeof PlanMealsRoute
  '/plan/occasion': typeof PlanOccasionRoute
  '/plan/review': typeof PlanReviewRoute
  '/plan/side': typeof PlanSideRoute
  '/plan/venue': typeof PlanVenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/plan/confirm': typeof PlanConfirmRoute
  '/plan/dates': typeof PlanDatesRoute
  '/plan/guests': typeof PlanGuestsRoute
  '/plan/intro': typeof PlanIntroRoute
  '/plan/meals': typeof PlanMealsRoute
  '/plan/occasion': typeof PlanOccasionRoute
  '/plan/review': typeof PlanReviewRoute
  '/plan/side': typeof PlanSideRoute
  '/plan/venue': typeof PlanVenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan'
    | '/welcome'
    | '/plan/confirm'
    | '/plan/dates'
    | '/plan/guests'
    | '/plan/intro'
    | '/plan/meals'
    | '/plan/occasion'
    | '/plan/review'
    | '/plan/side'
    | '/plan/venue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan'
    | '/welcome'
    | '/plan/confirm'
    | '/plan/dates'
    | '/plan/guests'
    | '/plan/intro'
    | '/plan/meals'
    | '/plan/occasion'
    | '/plan/review'
    | '/plan/side'
    | '/plan/venue'
  id:
    | '__root__'
    | '/'
    | '/plan'
    | '/welcome'
    | '/plan/confirm'
    | '/plan/dates'
    | '/plan/guests'
    | '/plan/intro'
    | '/plan/meals'
    | '/plan/occasion'
    | '/plan/review'
    | '/plan/side'
    | '/plan/venue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanRoute: typeof PlanRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/venue': {
      id: '/plan/venue'
      path: '/venue'
      fullPath: '/plan/venue'
      preLoaderRoute: typeof PlanVenueRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/side': {
      id: '/plan/side'
      path: '/side'
      fullPath: '/plan/side'
      preLoaderRoute: typeof PlanSideRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/review': {
      id: '/plan/review'
      path: '/review'
      fullPath: '/plan/review'
      preLoaderRoute: typeof PlanReviewRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/occasion': {
      id: '/plan/occasion'
      path: '/occasion'
      fullPath: '/plan/occasion'
      preLoaderRoute: typeof PlanOccasionRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/meals': {
      id: '/plan/meals'
      path: '/meals'
      fullPath: '/plan/meals'
      preLoaderRoute: typeof PlanMealsRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/intro': {
      id: '/plan/intro'
      path: '/intro'
      fullPath: '/plan/intro'
      preLoaderRoute: typeof PlanIntroRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/guests': {
      id: '/plan/guests'
      path: '/guests'
      fullPath: '/plan/guests'
      preLoaderRoute: typeof PlanGuestsRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/dates': {
      id: '/plan/dates'
      path: '/dates'
      fullPath: '/plan/dates'
      preLoaderRoute: typeof PlanDatesRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/confirm': {
      id: '/plan/confirm'
      path: '/confirm'
      fullPath: '/plan/confirm'
      preLoaderRoute: typeof PlanConfirmRouteImport
      parentRoute: typeof PlanRoute
    }
  }
}

interface PlanRouteChildren {
  PlanConfirmRoute: typeof PlanConfirmRoute
  PlanDatesRoute: typeof PlanDatesRoute
  PlanGuestsRoute: typeof PlanGuestsRoute
  PlanIntroRoute: typeof PlanIntroRoute
  PlanMealsRoute: typeof PlanMealsRoute
  PlanOccasionRoute: typeof PlanOccasionRoute
  PlanReviewRoute: typeof PlanReviewRoute
  PlanSideRoute: typeof PlanSideRoute
  PlanVenueRoute: typeof PlanVenueRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanConfirmRoute: PlanConfirmRoute,
  PlanDatesRoute: PlanDatesRoute,
  PlanGuestsRoute: PlanGuestsRoute,
  PlanIntroRoute: PlanIntroRoute,
  PlanMealsRoute: PlanMealsRoute,
  PlanOccasionRoute: PlanOccasionRoute,
  PlanReviewRoute: PlanReviewRoute,
  PlanSideRoute: PlanSideRoute,
  PlanVenueRoute: PlanVenueRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanRoute: PlanRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
